stages:
  - fossid
  - clean-fossid


fossid:
  tags:
    - FOSSID
  stage: fossid
  script:
    - fossid_check.sh
  artifacts:
    paths:
    - fossid*.txt
  when: manual

clean-fossid:
  stage: clean-fossid
  tags:
    - FOSSID
  script:
    - rm -rf * .git .git*
    - ls -a
    - ls -a ..
  when: always
  
